"""One-shot: add Edgemont Weidler as an 8th project to the "Remove Rochelle -
Add Edgemont" variant scenario, adopting the scenario's existing shared
Raymond James Bond for its sources.

Copies the INPUT subtree (milestones, operational inputs, income streams,
opex lines, use lines, fee-basis rows) from Edgemont's standalone model
(scenario dbf59d85 / project 1e201ccd) into variant scenario b22be693 as a
new sibling project. Outputs are regenerated by ``compute_cash_flows``.

Design decisions:
  * NO capital modules are copied. The variant scenario already has one
    shared "Raymond James Bond (auto)" module junctioned to all 7 projects;
    the new project joins that junction (auto-sized, so recompute sizes its
    slice). Edgemont's standalone Owner Equity / Deferred Developer Fee
    modules are intentionally left behind — "Sources should just be
    adopting the Raymond James Bond".
  * Use lines that reference Edgemont's own bond module
    (source_capital_module_id, eligible_module_ids, fee-basis rows) are
    remapped to the variant's shared bond.
  * The auto finance-cost use line is skipped — compute regenerates it from
    the shared bond. Auto Dev Fee lines are copied (engine only updates
    existing rows; see consolidate_unified_underwriting).
  * Waterfall tiers are NOT copied — the variant scenario already has its
    own waterfall configuration.

Run on VM 114 inside the api container, dry-run first::

    docker exec vicinitideals-api python -m app.scripts.add_edgemont_to_variant
    docker exec vicinitideals-api python -m app.scripts.add_edgemont_to_variant --commit
"""

from __future__ import annotations

import argparse
import asyncio
import copy
import sys
from uuid import UUID

from sqlalchemy import select

from app.db import AsyncSessionLocal
from app.models.capital import (
    CapitalModule,
    CapitalModuleProject,
    UseLineSourceFeeBasis,
)
from app.models.deal import (
    IncomeStream,
    OperatingExpenseLine,
    OperationalInputs as _OpInputs,
    Scenario,
    UseLine,
)
from app.models.milestone import Milestone
from app.models.project import Project

VARIANT_SCENARIO_ID = UUID("b22be693-fa53-4ced-9c8e-7be0ca52c390")
SRC_PROJECT_ID = UUID("1e201ccd-ab23-4432-be1a-662dc0d09b35")  # Edgemont standalone
SRC_BOND_ID = UUID("eaca5dce-19be-4b70-a7fe-f40c7e399a5a")     # Edgemont's own RJ bond
NEW_PROJECT_NAME = "Edgemont Weidler"

_TS = ("created_at", "updated_at")


def _clone(obj, **overrides):
    """New ORM instance copying every column except PK/timestamps; JSON values
    deep-copied. ``overrides`` replace specific columns (FKs)."""
    data = {}
    for col in obj.__table__.columns:
        key = col.key
        if key == "id" or key in _TS:
            continue
        val = getattr(obj, key)
        if isinstance(val, (dict, list)):
            val = copy.deepcopy(val)
        data[key] = val
    data.update(overrides)
    return type(obj)(**data)


def _remap(value, id_map):
    if value is None:
        return None
    return id_map.get(value, value)


def _remap_release_schedule(release, ms_map):
    if not release or not isinstance(release, dict):
        return release
    out = copy.deepcopy(release)
    for w in out.get("weights", []) or []:
        mid = w.get("milestone_id")
        if mid:
            w["milestone_id"] = str(_remap(UUID(str(mid)), ms_map))
    fh = out.get("final_holdback")
    if isinstance(fh, dict) and fh.get("milestone_id"):
        fh["milestone_id"] = str(_remap(UUID(str(fh["milestone_id"])), ms_map))
    return out


async def run(commit: bool, run_compute: bool) -> None:
    async with AsyncSessionLocal() as session:
        variant = await session.get(Scenario, VARIANT_SCENARIO_ID)
        if variant is None:
            print("FATAL: variant scenario not found", file=sys.stderr)
            return
        src_proj = await session.get(Project, SRC_PROJECT_ID)
        if src_proj is None:
            print("FATAL: source project not found", file=sys.stderr)
            return

        # The variant's shared bond — the one every existing project adopts.
        shared_bond = (await session.execute(
            select(CapitalModule).where(
                CapitalModule.scenario_id == VARIANT_SCENARIO_ID,
                CapitalModule.vehicle_type == "debt",
            )
        )).scalar_one()
        print(f"Shared bond: {shared_bond.id} — {shared_bond.label}")

        # Guard against double-run
        dupe = (await session.execute(
            select(Project).where(
                Project.scenario_id == VARIANT_SCENARIO_ID,
                Project.name == NEW_PROJECT_NAME,
            )
        )).scalars().first()
        if dupe is not None:
            print(f"FATAL: project '{NEW_PROJECT_NAME}' already exists ({dupe.id})",
                  file=sys.stderr)
            return

        module_map = {SRC_BOND_ID: shared_bond.id}
        counts = {k: 0 for k in (
            "milestones", "op_inputs", "income", "opex", "use_lines",
            "fee_basis", "junctions",
        )}

        # a. Project
        new_proj = _clone(src_proj, scenario_id=VARIANT_SCENARIO_ID,
                          name=NEW_PROJECT_NAME)
        session.add(new_proj)
        await session.flush()
        print(f"New project: {new_proj.id} — {new_proj.name}")

        # b. Milestones (two-pass trigger-chain remap)
        src_ms = (await session.execute(
            select(Milestone).where(Milestone.project_id == SRC_PROJECT_ID)
        )).scalars().all()
        ms_map: dict[UUID, UUID] = {}
        new_ms_by_old: dict[UUID, Milestone] = {}
        for m in src_ms:
            nm = _clone(m, project_id=new_proj.id, opportunity_id=None,
                        trigger_milestone_id=None)
            session.add(nm)
            await session.flush()
            ms_map[m.id] = nm.id
            new_ms_by_old[m.id] = nm
            counts["milestones"] += 1
        for m in src_ms:
            if m.trigger_milestone_id is not None:
                new_ms_by_old[m.id].trigger_milestone_id = ms_map.get(m.trigger_milestone_id)

        # c. OperationalInputs
        op = (await session.execute(
            select(_OpInputs).where(_OpInputs.project_id == SRC_PROJECT_ID)
        )).scalar_one_or_none()
        if op is not None:
            session.add(_clone(op, project_id=new_proj.id))
            counts["op_inputs"] += 1

        # d. Income streams + opex lines
        for inc in (await session.execute(
            select(IncomeStream).where(IncomeStream.project_id == SRC_PROJECT_ID)
        )).scalars().all():
            session.add(_clone(inc, project_id=new_proj.id))
            counts["income"] += 1
        for ex in (await session.execute(
            select(OperatingExpenseLine).where(OperatingExpenseLine.project_id == SRC_PROJECT_ID)
        )).scalars().all():
            session.add(_clone(ex, project_id=new_proj.id))
            counts["opex"] += 1

        # e. Use lines (skip auto finance-cost rows; remap module + milestone refs)
        src_uls = (await session.execute(
            select(UseLine).where(UseLine.project_id == SRC_PROJECT_ID)
        )).scalars().all()
        ul_map: dict[UUID, UUID] = {}
        for ul in src_uls:
            if getattr(ul, "is_auto_finance_cost", False):
                print(f"  skip auto finance-cost line: {ul.label}")
                continue
            elig = getattr(ul, "eligible_module_ids", None)
            new_elig = [_remap(m, module_map) for m in elig] if elig else elig
            nm_ul = _clone(
                ul,
                project_id=new_proj.id,
                active_from_milestone_id=_remap(ul.active_from_milestone_id, ms_map),
                spread_to_milestone_id=_remap(ul.spread_to_milestone_id, ms_map),
                source_capital_module_id=_remap(ul.source_capital_module_id, module_map),
                eligible_module_ids=new_elig,
                dev_fee_release_schedule=_remap_release_schedule(
                    ul.dev_fee_release_schedule, ms_map),
                dev_fee_binding_context={},  # output — regenerated on compute
            )
            session.add(nm_ul)
            await session.flush()
            ul_map[ul.id] = nm_ul.id
            counts["use_lines"] += 1

        # f. Fee-basis rows (only those pointing at the remappable bond)
        if ul_map:
            for fb in (await session.execute(
                select(UseLineSourceFeeBasis).where(
                    UseLineSourceFeeBasis.use_line_id.in_(list(ul_map.keys()))
                )
            )).scalars().all():
                new_cm = module_map.get(fb.capital_module_id)
                if new_cm is None:
                    print(f"  skip fee-basis row on non-adopted module {fb.capital_module_id}")
                    continue
                session.add(_clone(fb, use_line_id=ul_map[fb.use_line_id],
                                   capital_module_id=new_cm))
                counts["fee_basis"] += 1

        # g. Junction: new project adopts the shared Raymond James Bond.
        # Clone Edgemont's own bond junction so amount seed / windows carry over;
        # recompute resizes (auto_size).
        src_cmp = (await session.execute(
            select(CapitalModuleProject).where(
                CapitalModuleProject.project_id == SRC_PROJECT_ID,
                CapitalModuleProject.capital_module_id == SRC_BOND_ID,
            )
        )).scalar_one()
        session.add(_clone(
            src_cmp,
            capital_module_id=shared_bond.id,
            project_id=new_proj.id,
            active_from_milestone_id=_remap(src_cmp.active_from_milestone_id, ms_map),
            active_to_milestone_id=_remap(src_cmp.active_to_milestone_id, ms_map),
        ))
        counts["junctions"] += 1

        await session.flush()

        print("── Summary ──")
        for k, v in counts.items():
            print(f"  {k:<12}: {v}")

        if not commit:
            await session.rollback()
            print("\nDRY RUN — rolled back. Re-run with --commit to persist.")
            return

        await session.commit()
        print("\nCOMMITTED.")
        new_proj_id = new_proj.id

        if run_compute:
            from app.engines.cashflow import compute_cash_flows
            print("Computing variant scenario …")
            async with AsyncSessionLocal() as cs:
                await compute_cash_flows(deal_model_id=VARIANT_SCENARIO_ID, session=cs)
                await cs.commit()
            print("Compute complete.")
        print(f"\nOpen: /models/{VARIANT_SCENARIO_ID}/builder?project={new_proj_id}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--commit", action="store_true", help="persist (default: dry-run + rollback)")
    ap.add_argument("--no-compute", action="store_true", help="skip recompute after commit")
    args = ap.parse_args()
    asyncio.run(run(commit=args.commit, run_compute=not args.no_compute))


if __name__ == "__main__":
    main()
