"""One-shot: consolidate 8 existing single-project deals into one host Scenario.

Deep-copies each source deal's Project (with its full INPUT subtree — milestones,
operational inputs, use lines, income streams, opex lines, capital modules +
junctions, waterfall tiers, anchors) into a single new host Scenario as 8 sibling
projects. Outputs (cash flows, operational outputs, waterfall results, draw
events) are NOT copied — they are regenerated by ``compute_cash_flows``.

Design decisions (per the unified-underwriting build):
  * Per-project bond slices, ONE pool. Each project keeps its own Raymond James
    Bond module at its exact amount so its float/T-yield stays correct (float
    reads the parent module's whole ``source['amount']``). Bond labels are
    normalised to "Raymond James Bond" so they read as one source. We do NOT
    collapse into a single module (that would 8x the T-yields) and do NOT force a
    shared source_vehicle_id (that could rewrite fee_terms on projects that don't
    currently use the preset).
  * The two intentionally net-negative projects are copied verbatim. Their bonds
    fund the capital budget only; operating deficits surface as negative monthly
    net cash flow that drags the combined bank account — no masking source.

Row cloning is introspection-based (copy every column verbatim except the PK and
timestamps) so we never silently drop a field the way the legacy
``_copy_project_data`` helper does. FK references that point at other copied rows
(milestone trigger chains, capital-module windows, float parent_module_id, dev
fee release schedules, use-line eligibility) are remapped to the new ids.

Run on VM 114 inside the api container, dry-run first::

    docker exec vicinitideals-api python -m app.scripts.consolidate_unified_underwriting
    docker exec vicinitideals-api python -m app.scripts.consolidate_unified_underwriting --commit

Dry-run builds the whole graph in a transaction and rolls back, printing a
summary. ``--commit`` persists and (unless ``--no-compute``) recomputes the host
scenario so it is immediately evaluable.
"""

from __future__ import annotations

import argparse
import asyncio
import copy
import sys
from uuid import UUID

from sqlalchemy import select

from app.db import AsyncSessionLocal
from app.models.capital import (
    CapitalModule,
    CapitalModuleProject,
    UseLineSourceFeeBasis,
    WaterfallTier,
)
from app.models.deal import (
    Deal,
    IncomeStream,
    OperatingExpenseLine,
    OperationalInputs as _OpInputs,
    Scenario,
    UseLine,
)
from app.models.milestone import Milestone
from app.models.project import Project, ProjectAnchor

# ── The 8 (host source for the bond is 0ab276ba). (scenario_id, project_id) ──
SOURCES: list[tuple[str, str]] = [
    ("e125ba7c-a029-4d17-a52b-3aca201b9834", "861fdd62-c0bc-4fa9-8653-54b791f2e1a2"),  # gap-fill #1 (net-neg)
    ("fbb4a707-b27e-4828-a0b1-16e6f037b04b", "294998e7-2fd4-4fcc-9b83-d4dcd6d737ed"),  # gap-fill #2 (net-neg)
    ("3aacba25-d5ce-406d-bd81-9e1a3efc218f", "9f9bca13-65eb-42a4-8e80-9e0cb03e1a9e"),  # Fessenden (has T-yield)
    ("21a79209-e905-4a3b-8983-764e80a25777", "4a05be4a-e8e2-4812-9dd4-0d882bd6b241"),
    ("0ab276ba-99c8-429a-9957-de155912c6e0", "a313f23f-dc24-4038-b1b7-827e3fc989fe"),  # Raymond James source
    ("4a4e70cf-7255-4eb8-be4e-5fc9768194f9", "a28009d9-abc4-4351-98ec-722a7af176d1"),
    ("21ff592c-1c67-4d64-8e29-b321612f105a", "4ad52e50-1c88-424b-a6c3-0878eeb05d68"),  # Rochelle
    ("cf0e77c3-a445-434c-8788-6d948303d916", "c1e823ce-c406-4aa0-8d25-633b9dca12f4"),  # has Float Earnings
]

HOST_DEAL_NAME = "Unified Underwriting — 8 Projects"
HOST_SCENARIO_NAME = "Combined Pool"
_TS = ("created_at", "updated_at")


def _clone(obj, **overrides):
    """Return a new ORM instance copying every column verbatim except the PK
    and timestamps. JSON/dict/list values are deep-copied so later remaps never
    mutate the source row. ``overrides`` replace specific columns (FKs)."""
    data = {}
    for col in obj.__table__.columns:
        key = col.key
        if key == "id" or key in _TS:
            continue
        val = getattr(obj, key)
        if isinstance(val, (dict, list)):
            val = copy.deepcopy(val)
        data[key] = val
    data.update(overrides)
    return type(obj)(**data)


def _remap(value, id_map: dict[UUID, UUID]):
    """Map an id through id_map; pass through None and unknown ids unchanged."""
    if value is None:
        return None
    return id_map.get(value, value)


def _is_auto_use_line(ul: UseLine) -> bool:
    # Only skip finance-cost rows: compute_cash_flows regenerates those from the
    # (re)sized debt on every run. Auto Dev Fee and Acquisition Fee rows are NOT
    # regenerated from scratch — recompute_auto_dev_fee only *updates an existing*
    # row (returns early when the auto line is absent), so dropping them here would
    # permanently delete each project's developer fee / acquisition fee. Copy them.
    return bool(getattr(ul, "is_auto_finance_cost", False))


def _normalise_bond_label(module: CapitalModule) -> None:
    if (module.vehicle_type or "") != "debt":
        return
    label = (module.label or "").lower()
    if "raymond" in label or "rj bond" in label:
        module.label = "Raymond James Bond"


async def consolidate(commit: bool, run_compute: bool) -> None:
    async with AsyncSessionLocal() as session:
        src_pairs = [(UUID(s), UUID(p)) for s, p in SOURCES]

        # ── Host Deal + Scenario, inheriting org/user/type from first source ──
        first_scn = await session.get(Scenario, src_pairs[0][0])
        if first_scn is None:
            print(f"FATAL: source scenario {src_pairs[0][0]} not found", file=sys.stderr)
            return
        first_deal = await session.get(Deal, first_scn.deal_id)

        host_deal = Deal(
            org_id=first_deal.org_id,
            created_by_user_id=first_deal.created_by_user_id,
            name=HOST_DEAL_NAME,
        )
        session.add(host_deal)
        await session.flush()

        host_scn = Scenario(
            deal_id=host_deal.id,
            created_by_user_id=first_scn.created_by_user_id,
            name=HOST_SCENARIO_NAME,
            project_type=first_scn.project_type,
            income_mode=first_scn.income_mode,
            # Scenario-level financial settings drive engine behaviour that is NOT
            # captured in per-project rows — notably risk_free_rate_pct, which the
            # float/T-yield engine reads to value Treasury earnings on drawn bond
            # balances. A NULL host rate silently zeroes every project's float.
            # Inherit the full settings block from the first source scenario.
            risk_free_rate_pct=first_scn.risk_free_rate_pct,
            discount_rate_pct=first_scn.discount_rate_pct,
            min_reserve_construction=first_scn.min_reserve_construction,
            min_reserve_operational=first_scn.min_reserve_operational,
            health_thresholds=first_scn.health_thresholds,
        )
        session.add(host_scn)
        await session.flush()

        global_project_map: dict[UUID, UUID] = {}
        global_ms_map: dict[UUID, UUID] = {}
        anchors_to_wire: list[ProjectAnchor] = []
        counts = {k: 0 for k in (
            "projects", "milestones", "op_inputs", "use_lines", "income", "opex",
            "modules", "junctions", "waterfall_tiers", "fee_basis",
        )}

        for src_scn_id, src_proj_id in src_pairs:
            src_proj = await session.get(Project, src_proj_id)
            if src_proj is None:
                print(f"FATAL: project {src_proj_id} not found", file=sys.stderr)
                return

            # a. Project
            new_proj = _clone(src_proj, scenario_id=host_scn.id)
            session.add(new_proj)
            await session.flush()
            global_project_map[src_proj_id] = new_proj.id
            counts["projects"] += 1

            # b. Milestones (two-pass trigger-chain remap)
            src_ms = (await session.execute(
                select(Milestone).where(Milestone.project_id == src_proj_id)
            )).scalars().all()
            ms_map: dict[UUID, UUID] = {}
            new_ms_by_old: dict[UUID, Milestone] = {}
            for m in src_ms:
                nm = _clone(m, project_id=new_proj.id, opportunity_id=None,
                            trigger_milestone_id=None)
                session.add(nm)
                await session.flush()
                ms_map[m.id] = nm.id
                new_ms_by_old[m.id] = nm
                counts["milestones"] += 1
            for m in src_ms:  # pass 2 — wire trigger ids
                if m.trigger_milestone_id is not None:
                    new_ms_by_old[m.id].trigger_milestone_id = ms_map.get(m.trigger_milestone_id)
            global_ms_map.update(ms_map)

            # c. OperationalInputs (1:1)
            op = (await session.execute(
                select(_OpInputs).where(_OpInputs.project_id == src_proj_id)
            )).scalar_one_or_none()
            if op is not None:
                session.add(_clone(op, project_id=new_proj.id))
                counts["op_inputs"] += 1

            # d. Income streams + opex lines
            for inc in (await session.execute(
                select(IncomeStream).where(IncomeStream.project_id == src_proj_id)
            )).scalars().all():
                session.add(_clone(inc, project_id=new_proj.id))
                counts["income"] += 1
            for ex in (await session.execute(
                select(OperatingExpenseLine).where(OperatingExpenseLine.project_id == src_proj_id)
            )).scalars().all():
                session.add(_clone(ex, project_id=new_proj.id))
                counts["opex"] += 1

            # e. Capital modules (every module of the single-project source scenario)
            src_modules = (await session.execute(
                select(CapitalModule).where(CapitalModule.scenario_id == src_scn_id)
            )).scalars().all()
            module_map: dict[UUID, UUID] = {}
            new_mod_by_old: dict[UUID, CapitalModule] = {}
            for cm in src_modules:
                nm_cm = _clone(
                    cm,
                    scenario_id=host_scn.id,
                    active_from_milestone_id=_remap(cm.active_from_milestone_id, ms_map),
                    active_to_milestone_id=_remap(cm.active_to_milestone_id, ms_map),
                )
                session.add(nm_cm)
                await session.flush()
                module_map[cm.id] = nm_cm.id
                new_mod_by_old[cm.id] = nm_cm
                counts["modules"] += 1
            # post: float parent remap + bond label normalise
            for cm in src_modules:
                nm_cm = new_mod_by_old[cm.id]
                _normalise_bond_label(nm_cm)
                src_json = nm_cm.source or {}
                if (nm_cm.vehicle_type or "") == "float_earnings":
                    new_src = copy.deepcopy(src_json)
                    if src_json.get("parent_module_id"):
                        parent_old = UUID(str(src_json["parent_module_id"]))
                        new_src["parent_module_id"] = str(_remap(parent_old, module_map))
                    # Float earnings route to the waterfall at a milestone period.
                    # That milestone id must be remapped to this project's cloned
                    # milestone — otherwise the routing target doesn't exist in the
                    # host scenario and the earnings silently zero out.
                    for _ms_key in ("waterfall_milestone_id", "paydown_milestone_id"):
                        _old_ms = src_json.get(_ms_key)
                        if _old_ms:
                            new_src[_ms_key] = str(_remap(UUID(str(_old_ms)), ms_map))
                    nm_cm.source = new_src

            # f. Capital-module-project junctions (synthesise if missing)
            existing_cmp = (await session.execute(
                select(CapitalModuleProject).where(CapitalModuleProject.project_id == src_proj_id)
            )).scalars().all()
            cmp_by_module = {c.capital_module_id: c for c in existing_cmp}
            for cm in src_modules:
                old_cmp = cmp_by_module.get(cm.id)
                if old_cmp is not None:
                    session.add(_clone(
                        old_cmp,
                        capital_module_id=module_map[cm.id],
                        project_id=new_proj.id,
                        active_from_milestone_id=_remap(old_cmp.active_from_milestone_id, ms_map),
                        active_to_milestone_id=_remap(old_cmp.active_to_milestone_id, ms_map),
                    ))
                else:
                    # single-project scenario without an explicit junction: bind the
                    # module to the project at its stored amount / auto_size.
                    src_json = cm.source or {}
                    session.add(CapitalModuleProject(
                        capital_module_id=module_map[cm.id],
                        project_id=new_proj.id,
                        amount=src_json.get("amount") or 0,
                        auto_size=bool(src_json.get("auto_size", False)),
                    ))
                counts["junctions"] += 1

            # g. Use lines (skip engine-regenerated auto rows; remap refs)
            src_uls = (await session.execute(
                select(UseLine).where(UseLine.project_id == src_proj_id)
            )).scalars().all()
            ul_map: dict[UUID, UUID] = {}
            for ul in src_uls:
                if _is_auto_use_line(ul):
                    continue
                elig = getattr(ul, "eligible_module_ids", None)
                new_elig = [str(_remap(UUID(str(m)), module_map)) for m in elig] if elig else elig
                release = getattr(ul, "dev_fee_release_schedule", None)
                new_release = _remap_release_schedule(release, ms_map)
                nm_ul = _clone(
                    ul,
                    project_id=new_proj.id,
                    active_from_milestone_id=_remap(getattr(ul, "active_from_milestone_id", None), ms_map),
                    spread_to_milestone_id=_remap(getattr(ul, "spread_to_milestone_id", None), ms_map),
                    source_capital_module_id=_remap(getattr(ul, "source_capital_module_id", None), module_map),
                    eligible_module_ids=new_elig,
                    dev_fee_release_schedule=new_release,
                    dev_fee_binding_context={},  # output — regenerated on compute
                )
                session.add(nm_ul)
                await session.flush()
                ul_map[ul.id] = nm_ul.id
                counts["use_lines"] += 1

            # h. Waterfall tiers (scenario-scoped)
            for wt in (await session.execute(
                select(WaterfallTier).where(WaterfallTier.scenario_id == src_scn_id)
            )).scalars().all():
                session.add(_clone(
                    wt,
                    scenario_id=host_scn.id,
                    project_id=_remap(wt.project_id, global_project_map),
                    capital_module_id=_remap(wt.capital_module_id, module_map),
                ))
                counts["waterfall_tiers"] += 1

            # i. Use-line source fee-basis rows
            if ul_map:
                for fb in (await session.execute(
                    select(UseLineSourceFeeBasis).where(
                        UseLineSourceFeeBasis.use_line_id.in_(list(ul_map.keys()))
                    )
                )).scalars().all():
                    new_ul = ul_map.get(fb.use_line_id)
                    new_cm = module_map.get(fb.capital_module_id)
                    if new_ul and new_cm:
                        session.add(_clone(fb, use_line_id=new_ul, capital_module_id=new_cm))
                        counts["fee_basis"] += 1

            # j. Project anchors deferred (need global maps across all projects)
            anchor = (await session.execute(
                select(ProjectAnchor).where(ProjectAnchor.project_id == src_proj_id)
            )).scalar_one_or_none()
            if anchor is not None:
                anchors_to_wire.append(anchor)

        # ── Global pass: anchors (cross-project trigger coupling) ──
        anchors_wired = 0
        for a in anchors_to_wire:
            new_pid = global_project_map.get(a.project_id)
            new_anchor_pid = global_project_map.get(a.anchor_project_id)
            if new_pid is None or new_anchor_pid is None:
                print(f"  skip anchor {a.id}: references a project outside the set")
                continue
            session.add(_clone(
                a,
                project_id=new_pid,
                anchor_project_id=new_anchor_pid,
                anchor_milestone_id=_remap(a.anchor_milestone_id, global_ms_map),
            ))
            anchors_wired += 1

        await session.flush()

        print("── Consolidation summary ──")
        print(f"  host deal     : {host_deal.id}")
        print(f"  host scenario : {host_scn.id}")
        for k, v in counts.items():
            print(f"  {k:<16}: {v}")
        print(f"  anchors_wired   : {anchors_wired}")

        if not commit:
            await session.rollback()
            print("\nDRY RUN — rolled back. Re-run with --commit to persist.")
            return

        await session.commit()
        print("\nCOMMITTED.")

        if run_compute:
            from app.engines.cashflow import compute_cash_flows
            print("Computing host scenario …")
            async with AsyncSessionLocal() as cs:
                await compute_cash_flows(deal_model_id=host_scn.id, session=cs)
                await cs.commit()
            print("Compute complete.")
        print(f"\nOpen: /models/{host_scn.id}/builder")


def _remap_release_schedule(release, ms_map: dict[UUID, UUID]):
    """Remap milestone ids embedded in a dev_fee_release_schedule JSONB.

    Shape: {"weights": [{"milestone_id", "weight"}], "final_holdback": {"milestone_id", "pct"}}.
    """
    if not release or not isinstance(release, dict):
        return release
    out = copy.deepcopy(release)
    for w in out.get("weights", []) or []:
        mid = w.get("milestone_id")
        if mid:
            w["milestone_id"] = str(_remap(UUID(str(mid)), ms_map))
    fh = out.get("final_holdback")
    if isinstance(fh, dict) and fh.get("milestone_id"):
        fh["milestone_id"] = str(_remap(UUID(str(fh["milestone_id"])), ms_map))
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--commit", action="store_true", help="persist (default: dry-run + rollback)")
    ap.add_argument("--no-compute", action="store_true", help="skip recompute after commit")
    args = ap.parse_args()
    asyncio.run(consolidate(commit=args.commit, run_compute=not args.no_compute))


if __name__ == "__main__":
    main()
